version: '3'

services:
  nginx-proxy:
    image: nginx:latest
    restart: always
    volumes:
      - "$PWD/nginx.config/:/etc/nginx/conf.d/"
      - "$PWD/certs/cert.pem:/path/to/fullchain.pem"
      - "$PWD/certs/key.pem:/path/to/privkey.pem"
    ports:
      - "443:443"


  # MySQL
  db:
    platform: linux/amd64
    image: mysql:5.6
    restart: always
    container_name: spohub-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: spohubdb
      MYSQL_USER: spohub
      MYSQL_PASSWORD: spohub
      TZ: 'Asia/Tokyo'
      VIRTUAL_HOST: db
      VIRTUAL_PORT: 3306
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 3s
      timeout: 30s
      retries: 10
    volumes:
    - ./sports-barrier-free-mysql/mysql/data:/var/lib/mysql
    - ./sports-barrier-free-mysql/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    - ./sports-barrier-free-mysql/mysql/db:/docker-entrypoint-initdb.d

